# Generated by Django 3.0.5 on 2020-05-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0003_auto_20200510_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='readtext',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
