# Generated by Django 3.0.5 on 2020-05-04 01:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='氏名')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('age', models.IntegerField(verbose_name='年齢')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='登録日時')),
            ],
            options={
                'db_table': 'customer',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CustomerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='支払い金額')),
                ('note', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='来店日時')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Customer')),
            ],
            options={
                'db_table': 'customer_log',
                'ordering': ('-created_at',),
            },
        ),
    ]
